[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remaapings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts']
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
ffi = true
fs_permissions = [{access = "read", path = "./img/"}]